### ISSUE TITLE
Compile time error

### ISSUE THREAD

**Issue by maximecarey** [newrelic/agent_sdk_samples#4]
I'm trying to build on Ubuntu 13.10 the HHVM plugin and I get this error :

```
Scanning dependencies of target newrelic
[100%] Building CXX object CMakeFiles/newrelic.dir/newrelic.cpp.o
/home/max/agent_sdk_samples/hhvm/extension/newrelic.cpp: In function ‘int HPHP::f_hhvm_newrelic_transaction_set_threshold(int)’:
/home/max/agent_sdk_samples/hhvm/extension/newrelic.cpp:118:73: error: ‘newrelic_transaction_set_threshold’ was not declared in this scope
  return newrelic_transaction_set_threshold(NEWRELIC_AUTOSCOPE, threshold);
                                                                         ^
```

Using latest HHVM sources and GCC 4.8.1. Any clues?
